# Generated by Django 5.0.6 on 2024-05-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Home_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=10)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('work', models.CharField(blank=True, max_length=255)),
                ('married', models.BooleanField()),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='App_Home.app_home_db')),
            ],
        ),
    ]
