# Generated by Django 5.0.6 on 2024-05-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=10)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('work', models.CharField(blank=True, max_length=255)),
                ('married', models.BooleanField()),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='App_Home.app_home_db')),
            ],
        ),
    ]
