# Generated by Django 5.0.6 on 2024-05-23 08:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('className', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdDate', models.DateField(default=datetime.datetime(2024, 5, 23, 8, 0, 58, 793878))),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.subject')),
            ],
        ),
    ]
