# Generated by Django 5.0.6 on 2024-05-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_subject_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='createdDate',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 8, 29, 52, 683785, tzinfo=datetime.timezone.utc)),
        ),
    ]
