# Generated by Django 5.0.6 on 2024-05-23 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_subject_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='createdDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
