# Generated by Django 5.0.6 on 2024-05-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_subject_createddate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_subject',
            unique_together={('studentInfo', 'subject')},
        ),
    ]
