# Generated by Django 5.0.6 on 2024-05-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_subject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
    ]
